---
- name: Setup OWASP ZAP container
  hosts: all
  gather_facts: yes
  collections:
    - containers.podman
  tasks:
    - name: Run DVWS container
      podman_container:
        name: dvws
        image: docker.io/cyrivs89/web-dvws
        state: present
        recreate: yes
        published_ports: 8080:80

    