---
- name: Setup OWASP ZAP container
  hosts: all
  gather_facts: yes
  collections:
    - containers.podman
  tasks:
    - name: Install required tools
      become: yes
      package:
        name: "{{ item }}"
        state: present
      loop:
        - podman
        - git 

    - name: Run mongo container
      podman_container:
        name: mongo
        image: mongo:4.0.4
        state: started

    - name: Run MSQL container
      podman_container:
        name: mysql
        image: mysql:5.7
        state: started
        env:
          MYSQL_ROOT_PASSWORD: mysecretpassword

    - name: Checkout DVWS repo
      git:
        repo: https://github.com/snoopysecurity/dvws-node.git
        dest: ~/dvws-node
        
    - name: create dvws image
      podman_image:
        name: dvws
        path: ~/dvws-node
        push: no 


    