---
- name: Setup OWASP ZAP container
  hosts: all
  gather_facts: yes
  collections:
    - containers.podman
  tasks:
    - name: Run mongo container
      podman_container:
        name: mongo
        image: mongo:4.0.4
        state: started

    - name: Run MSQL container
      podman_container:
        name: mysql
        image: mysql:5.7
        state: started
        env:
          MYSQL_ROOT_PASSWORD: mysecretpassword

    - name: create dvws image
      podman_image:
        name: dvws
        path: https://github.com/snoopysecurity/dvws-node.git
        push: no 


    